version: '3.9'

services:
  app:
    container_name: nest-app
    build: .
    command: npm run start:dev
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend

  db:
    container_name: nest-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
